// Card definitions used for the 2026-08-21 batch — copy and edit for new batches
export const cards = [
  { file:'01-workslop-40.png', mode:'dark', eyebrow:'The Dark Side of AI', big:'40', unit:'%',
    statement:'of US desk workers received AI “workslop” in a single month — work that looks right and isn’t.',
    sub:'Each incident takes ~1h 56m to untangle · ≈ $186 per worker per month',
    conf:'HIGH', source:'BetterUp Labs × Stanford Social Media Lab · HBR, Sep 2025' },
  { file:'02-datacenter-500b.png', mode:'light', eyebrow:'Infrastructure Report', big:'$500', unit:'B',
    statement:'the cost of one 10-gigawatt AI data center. Roughly two thirds of it is chips — the building is the cheap part.',
    sub:'Includes a 9.2GW on-site gas power station',
    conf:'MEDIUM', source:'US DOE · SoftBank · Mar 2026' },
  { file:'03-meta-blackrock.png', mode:'light', eyebrow:'Who Owns AI’s Data Centers', big:'80', unit:'%',
    statement:'of Meta’s $14.3B El Paso AI campus is now owned by BlackRock-managed funds. Meta keeps 20% — and every operational lever.',
    sub:'Second deal of its kind in ten months · ≈ $41B moved off balance sheet',
    conf:'HIGH', source:'Meta investor release · Reuters · Jul 2026' },
  { file:'04-adoption-88.png', mode:'chart', eyebrow:'Enterprise AI Adoption',
    title:'Organizations using AI, 2023–2026',
    bars:[{y:'2023',v:55},{y:'2024',v:72},{y:'2025',v:78},{y:'2026',v:88}], suffix:'%',
    conf:'HIGH', source:'McKinsey · State of AI / State of Organizations' },
  { file:'05-spend-259t.png', mode:'dark', eyebrow:'AI Economics', big:'$2.59', unit:'T',
    statement:'worldwide AI spending in 2026 — up 47% year over year.',
    sub:'≈ 41% of all IT spend now goes to AI',
    conf:'HIGH', source:'Gartner · May 2026' },
  { file:'06-inference-280x.png', mode:'dark', eyebrow:'LLM Token Price Index', big:'280', unit:'×',
    statement:'drop in GPT-3.5-class inference cost in under two years. Yesterday’s AI got absurdly cheap.',
    sub:'≈ 10× cheaper every year at fixed capability',
    conf:'HIGH', source:'Stanford HAI · AI Index' },
  { file:'07-deepfakes-98.png', mode:'dark', eyebrow:'The Dark Side of AI', big:'~98', unit:'%',
    statement:'of deepfakes are nonconsensual sexual imagery — not politics, not fraud.',
    sub:'The most common use of the technology, by far',
    conf:'HIGH', source:'Research compiled at Report AI' },
  { file:'08-aislop-74.png', mode:'light', eyebrow:'AI Slop', big:'74', unit:'%',
    statement:'of newly created web pages contain AI-generated content. The synthetic flood is the internet’s new baseline.',
    sub:'Generation cost fell to ~zero; evaluation cost didn’t',
    conf:'MEDIUM', source:'Ahrefs study · 2026' },
  { file:'09-assistants-900m.png', mode:'hbar', eyebrow:'The LLM Market',
    title:'Leading AI assistants — weekly active users',
    hbars:[{l:'ChatGPT',v:900},{l:'Gemini',v:650},{l:'Meta AI',v:600},{l:'Copilot',v:220},{l:'Claude',v:80},{l:'Perplexity',v:30}], hsuffix:'M',
    conf:'MEDIUM', source:'Provider-reported · 2026 · not independently audited' },
  { file:'10-doubao-382m.png', mode:'light', eyebrow:'The Geography of AI', big:'382', unit:'M',
    statement:'monthly users of Doubao in China — the world’s largest AI market runs on its own default, with Western models blocked.',
    sub:'8 of 11 major markets default to ChatGPT. The exceptions tell the story.',
    conf:'HIGH', source:'QuestMobile · May 2026' },
];
