# -*- coding: utf-8 -*-
"""Generate the ES/FR home pages from the v3 redesign.

The previous home-es/home-fr were built from home-961.html — the old .aa-hp
markup. The redesign replaced that wholesale, so regenerating from the new
source is the only way the three language versions stay the same page.

Three things this has to get right that gen_sx.py did not have to:

  data-report / data-dim   the assessment and dimension copy lives in JSON
                           attributes, not text nodes (see sx_home3)
  [aa_home_cohorts]        a shortcode, not markup — it gets lang="xx" rather
                           than being translated
  absolute URLs            the redesign links to https://agile-agilist.com/...
                           where the older pages used site-relative paths

Fails loudly rather than emitting a page with English left in it.
"""
import re, io, os, sys, html as _html
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sx, sx_home3, schema_clean, gen_sx
import translations_home as H
import translations_home3 as H3

SRC = "snippets/pages/home-961-v3-markup-only.html"
OUT = "/home/user/test/snippets/pages/translations"

ABS = "https://agile-agilist.com"


def build_table():
    """EN -> (es, fr), keyed on entity-normalised text."""
    t = {}
    for src in (H.HOME, H3.V3):
        for k, v in src.items():
            t[_html.unescape(k).strip()] = v
    keep = {_html.unescape(k).strip() for k in (H.KEEP | H3.KEEP)}
    return t, keep


def rewrite_url(u, lang):
    if u.startswith(ABS):
        u = u[len(ABS):] or "/"
    if u.startswith(("http", "#", "mailto:", "tel:")):
        return u
    if u.startswith("/"):
        return "/%s%s" % (lang, u)
    return u


def make_lookup(table, keep, lang, unresolved):
    """One resolver shared by text nodes and JSON attributes."""
    def resolve(raw):
        s = _html.unescape(raw).strip()
        if s in H3.NUM:                      # digits the noise filter would skip
            return raw.replace(raw.strip(), H3.NUM[s][0 if lang == "es" else 1])
        if not s or not sx.translatable(s) or s in keep:
            return raw
        pair = table.get(s)
        if pair is None:
            unresolved.append(s)
            return raw
        hit = pair[0] if lang == "es" else pair[1]
        return raw.replace(raw.strip(), hit) if raw.strip() != raw else hit
    return resolve


def generate(lang):
    table, keep = build_table()
    unresolved = []
    resolve = make_lookup(table, keep, lang, unresolved)
    html = io.open(SRC, encoding="utf-8").read()
    out = []

    for kind, tok in sx.shred(html):
        if kind == "skip":
            m = gen_sx.LD.fullmatch(tok)
            if m:
                body, _ = gen_sx.localize_schema(m.group(2), lang, unresolved)
                out.append(m.group(1) + body + m.group(3))
            else:
                out.append(tok)
            continue

        if kind == "tag":
            tok = re.sub(r'href="([^"]+)"',
                         lambda m: 'href="%s"' % rewrite_url(m.group(1), lang), tok)
            # data-report / data-dim payloads carry the panel copy
            tok = sx_home3.rewrite_attrs(tok, resolve)
            out.append(tok)
            continue

        # text: keep the shortcodes, translate everything around them
        parts = sx_home3.SHORTCODE_RE.split(tok)
        for i, part in enumerate(parts):
            if i % 2 == 1:                       # the shortcode's attribute string
                attrs = part.strip()
                out.append('[aa_home_cohorts%s lang="%s"]'
                           % ((" " + attrs) if attrs else "", lang))
            else:
                out.append(resolve(part))
        continue

    page = gen_sx.tidy("".join(out))
    page, notes = schema_clean.clean_html(page)
    # The English source carries its own install banner; the locale one replaces
    # it rather than sitting under it.
    page = re.sub(r'<!-- =+\n\s+AGILE AGILIST — HOME PAGE  \(English\).*?=+ -->\n*',
                  '', page, count=1, flags=re.S)
    return banner(lang) + page, unresolved, notes


def banner(lang):
    where = {"es": "/es/ — Spanish home page", "fr": "/fr/ — French home page"}[lang]
    return (
        "<!-- ============================================================\n"
        "     %s\n"
        "\n"
        "     PASTE THIS INTO A \"CUSTOM HTML\" BLOCK, and delete whatever block is\n"
        "     above it — the old Spanish/French page is a separate Group block and\n"
        "     replacing this one does not remove it.\n"
        "\n"
        "     Generated by tools/gen_home3.py from home-961-v3-markup-only.html.\n"
        "     Do not hand-edit: edit the English source and regenerate, or the\n"
        "     three language versions drift apart again.\n"
        "\n"
        "     Same three WPCode snippets as the English page — install them once,\n"
        "     they serve every locale. The cohort shortcodes carry lang=\"%s\",\n"
        "     which translates the card chrome and points each card at the\n"
        "     translated course page (/%s/spc/ rather than /training/adv-safe/spc/).\n"
        "\n"
        "     Certification names, the five dimension layer names, and the\n"
        "     assessment product names stay in English, exactly as they do on\n"
        "     the ES/FR course and services pages already live.\n"
        "     ============================================================ -->\n"
        % (where, lang, lang))


def main():
    failed = {}
    for lang in ("es", "fr"):
        page, unresolved, notes = generate(lang)
        if unresolved:
            failed[lang] = list(dict.fromkeys(unresolved))
            continue
        p = os.path.join(OUT, "home-%s.html" % lang)
        io.open(p, "w", encoding="utf-8").write(page)
        print("  wrote %-16s %6d bytes%s"
              % (os.path.basename(p), len(page),
                 ("  [stripped: %s]" % "; ".join(notes)) if notes else ""))
    if failed:
        for lang, segs in failed.items():
            print("\nUNRESOLVED %s: %d segments" % (lang, len(segs)))
            for s in segs:
                print("   %s" % s[:130])
        sys.exit(1)
    print("\nGenerated with zero unresolved segments.")


if __name__ == "__main__":
    main()
