"""Build the WordPress pieces of the Two Chasms v2 homepage from the design handoff.

Inputs (copied verbatim from the handoff zip):
  src/index.html  - static homepage (the design's production starting point)
  src/site.css    - the design's stylesheet

Outputs (in out/):
  home_content.html   - post_content for page 8 (front page), one wp:html block
  template_css.css    - v2 rules appended to template 7 ("Mutation - full width")
  masthead.html       - header markup for template 7
  colophon.html       - footer markup for template 7

Why scoping: template 7 still carries the older "Mutation" stylesheet, which the
/assess draft (page 13) depends on, and it reuses class names the v2 design also
uses (.btn, .band, .crossing, .workshop, .assess ...). v2 rules are therefore
prefixed with .tc and the homepage content is wrapped in <div class="tc">.
Masthead and colophon are site-wide, so their rules are emitted unscoped and
replace the old dark masthead.
"""
import re
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "src"
OUT = HERE / "out"
OUT.mkdir(exist_ok=True)

css = (SRC / "site.css").read_text()
html = (SRC / "index.html").read_text()

# Site-wide chrome: these selectors stay global.
GLOBAL = ("masthead", "brand", ".mark", ".nav", "colophon")


def split_rules(block):
    """Split a flat CSS block into (selector, body) pairs."""
    return re.findall(r"([^{}]+)\{([^{}]*)\}", block)


def scope(selector):
    parts = []
    for s in selector.split(","):
        s = s.strip()
        if s in ("*", "body"):
            return None  # body/universal handled by the theme + old sheet
        if s == ":root":
            parts.append(":root")
        elif any(g in s for g in GLOBAL):
            parts.append(s)
        else:
            parts.append(".tc " + s)
    return ",".join(parts)


def emit(block):
    out = []
    for sel, body in split_rules(block):
        sel = re.sub(r"/\*.*?\*/", "", sel, flags=re.S).strip()
        sc = scope(sel)
        if sc:
            out.append(f"{sc}{{{body}}}")
    return "\n".join(out)


css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
media = re.findall(r"(@media[^{]+)\{((?:[^{}]*\{[^{}]*\})+)\}", css)
flat = re.sub(r"@media[^{]+\{(?:[^{}]*\{[^{}]*\})+\}", "", css)

parts = [
    "/* ===== TWO CHASMS v2 (twochasms design handoff) =====\n"
    "   Generated by two-chasms/build_wp.py from the handoff site.css.\n"
    "   Homepage rules are scoped to .tc; masthead/colophon are site-wide. */",
    emit(flat),
]
for q, body in media:
    if "prefers-reduced-motion" in q:
        parts.append(q.strip() + "{.tc *{animation:none!important;transition:none!important}}")
    else:
        parts.append(q.strip() + "{" + emit(body) + "}")

# Neutralise what the older stylesheet leaks into same-named v2 components.
parts.append("""/* resets: older Mutation sheet -> v2 components */
.tc{font-family:var(--sans);color:var(--ink)}
.tc h1,.tc h2,.tc h3,.tc p{margin:0}
.tc em{font-style:normal;color:var(--amber)}
.tc .band--ink em{color:var(--amber-lt)}
.tc i{font-style:italic;color:inherit}
.tc .band{padding:0;background:none;color:inherit}
.tc .band.band--wash{background:var(--wash-2)}
.tc .band.band--ink{background:var(--ink);color:#fff}
.tc .hero .kicker{display:inline;margin:0}
.tc .actions{margin-top:0}
.tc .hero .actions{margin-top:6px}
.tc .btn{border:0;cursor:pointer}
.tc a.btn--amber,.tc a.btn--amber:hover,.tc a.btn--ink,.tc a.btn--ink:hover{color:#fff}
.tc a.btn--amber-lt,.tc a.btn--amber-lt:hover{color:var(--ink)}
.tc .crossing{color:var(--ink)}
.tc .crossing .label{color:var(--mute)}
.tc .workshop{border:0;border-top:3px solid var(--slate);transform:none}
.tc .workshop:hover{transform:none}
.tc .workshop__code{font-size:inherit;letter-spacing:inherit}
.tc .assess{max-width:var(--max)}
.tc .band--ink .lead--dark{color:var(--cloud)}
/* masthead CTA (kept off .btn so the old .btn rules cannot reach it) */
.mh-cta{display:inline-block;font-family:var(--mono);font-size:11.5px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;padding:10px 14px;background:var(--ink);color:#fff}
.mh-cta:hover{background:var(--amber);color:#fff}
.masthead{background:#fff;color:var(--ink)}
.colophon a{color:var(--mute)}.colophon a:hover{color:var(--amber)}
.colophon em{font-style:normal}
.nav a[aria-current="page"]{color:var(--ink);font-weight:600}
@media (prefers-reduced-motion:reduce){.mh-cta{transition:none}}""")

(OUT / "template_css.css").write_text("\n".join(parts) + "\n")

# ---- chrome ---------------------------------------------------------------
mast = re.search(r"<header class=\"masthead\">.*?</header>", html, re.S).group(0)
mast = mast.replace('href="index.html"', 'href="/"')
mast = mast.replace('<li class="is-current">', "<li>")
mast = mast.replace('<a class="btn btn--ink btn--sm" href="/books/">Pre-order</a>',
                    '<a class="mh-cta" href="/books/">Pre-order</a>')
(OUT / "masthead.html").write_text(mast + "\n")

colo = re.search(r"<footer class=\"wrap colophon\">.*?</footer>", html, re.S).group(0)
colo = colo.replace(
    "<span>The Two Chasms Framework · © Agile Agilist Inc. · Toronto</span>",
    "<span>The Two Chasms Framework · © Agile Agilist Inc. · Toronto · "
    "<a href=\"https://agile-agilist.com\">agile-agilist.com&nbsp;&#8599;</a></span>")
(OUT / "colophon.html").write_text(colo + "\n")

# ---- homepage body --------------------------------------------------------
main = re.search(r"<main>(.*?)</main>", html, re.S).group(1).strip()
# site.js equivalent: pause the SMIL banner for reduced-motion users.
js = ("<script>(function(){if(!window.matchMedia||!matchMedia('(prefers-reduced-motion: reduce)').matches)return;"
      "document.querySelectorAll('svg.journey').forEach(function(s){try{s.pauseAnimations();s.setCurrentTime(2.9);}catch(e){}});})();</script>")
# Handover §1 (locked): the third state is always "Signal Sensing", two capitalised words.
main = main.replace("Signal sensing", "Signal Sensing")
home = ("<!-- wp:html -->\n<div class=\"tc\">\n" + main + "\n</div>\n" + js + "\n<!-- /wp:html -->\n")
# Blank lines inside a wp:html block are harmless, but keep it compact.
home = re.sub(r"\n\s*\n", "\n", home)
(OUT / "home_content.html").write_text(home)

print({p.name: p.stat().st_size for p in OUT.iterdir()})
